### ISSUE TITLE
how to remove diagnosticMessages.generated.json

### ISSUE THREAD

**Issue by zuohuadong** [zeit/ncc#396]
![image](https://user-images.githubusercontent.com/11203929/57981275-3e2f8580-7a68-11e9-998d-9f07cf901c5f.png)

  142kB  dist/typescript/lib/zh-tw/diagnosticMessages.generated.json
  144kB  dist/typescript/lib/zh-cn/diagnosticMessages.generated.json
  153kB  dist/typescript/lib/cs/diagnosticMessages.generated.json
  160kB  dist/typescript/lib/tr/diagnosticMessages.generated.json
  161kB  dist/typescript/lib/pt-br/diagnosticMessages.generated.json
  164kB  dist/typescript/lib/es/diagnosticMessages.generated.json
  165kB  dist/typescript/lib/pl/diagnosticMessages.generated.json
  165kB  dist/typescript/lib/it/diagnosticMessages.generated.json
  165kB  dist/typescript/lib/fr/diagnosticMessages.generated.json
  167kB  dist/typescript/lib/de/diagnosticMessages.generated.json
  169kB  dist/typescript/lib/ko/diagnosticMessages.generated.json
  187kB  dist/typescript/lib/ja/diagnosticMessages.generated.json
  215kB  dist/typescript/lib/ru/diagnosticMessages.generated.json

**Comment by guybedford** [comment]
Because these files are used by TypeScript, and your app is using TypeScript, we need to include them in case those codepaths apply. Do you definitely need `require('typescript')` in this app?

We don't currently have explicit asset exclusions, but we do have debugging to work out why they are emitted if they aren't supposed to be.

I get the feeling the above are correct emissions though for supporting TypeScript execution.
