### ISSUE TITLE
What the difference of webpack 

### ISSUE THREAD

**Issue by a-x-** [zeit/ncc#424]
Read me does not clarify why we need ncc if we have a webpack 

Also, Can we use ncc for web and webpack for node?

3. Why we need to bundle node js code? What the benefit?

Can you add explanations to readme?

**Comment by a-x-** [comment]
One man recommends to use ncc in docker file to minimize it but he does not provide any details 

https://blog.webbylab.com/minimal_size_docker_image_for_your_nodejs_app/

**Comment by styfle** [comment]
There's not much difference if you're already using webpack.
Under the hood, ncc uses webpack.

The difference is the goals for `ncc` are more specific than webpack so that's why you typically can use `ncc` with zero configuration (ncc is designed for Node not for Web).

The benefit of bundling Node is faster startup which is important for [ZEIT Now](https://zeit.co/now). Read more about the concept of [cold start times and Lambdas](https://zeit.co/docs/v2/deployments/concepts/lambdas).

**Comment by a-x-** [comment]
Thank you

Can you share your benchmarks?
