### ISSUE TITLE
Out flag option does not work correctly

### ISSUE THREAD

**Issue by tunnckoCore** [zeit/ncc#70]
If you want the output to be printed to another file, different than `dist/index.js` you should use the `--out` flag, which describes that you should provide "out file".

But when you do

```
ncc build src/api.js --out dist/api.js
```

Then it creates a `dist/api.js/index.js` and not `dist/api.js` what we need.

**Comment by rauchg** [comment]
You should use `dist/api` and when you `require` don't use the `.js` suffix, so that you can support both situations (file or directory with `index.js`)

This is by design, because some Node programs need to output more side-effects

**Comment by rauchg** [comment]
That said, we could support `--out dist/api.js --single`, which would err if >1 outputs, and give you what you want. But is it really that necessary?

**Comment by tunnckoCore** [comment]
Why not just support `--out-dir` and `--out-file` ?

The `-o` / `--output` is usually a flag that allows making output file.

**Comment by tunnckoCore** [comment]
Currently, I'm using Rollup and the dist structure is the following

```
dist/index.js
dist/index-es.js
dist/api/index.js
dist/api/index-es.js
```

**Comment by rauchg** [comment]
Why not `dist/main/` `dist/main-es/` `dist/api/` `dist/api-es/` ?

**Comment by tunnckoCore** [comment]
Hm. Maybe.

**Comment by rauchg** [comment]
I'd be down to discuss `-f / --out-file`, but I think the idea that can you can treat a directory or a file the same (because the directory can resolve to `/index.js`) is *quite powerful*

For example, I spent some time thinking how `ncc` could use the CLI instead of the JS API for self-hosting.

- We'd rename `index.js` to `main.js`
- We'd make `cli.js` require (`./main`). This is important, because `main` written like that can resolve to both dir and file
- Then we'd export like this:

```
ncc build src/main -o dist/main
ncc build src/cli -e './main' -o dist/cli
```

`-e` is necessary to avoid the CLI bundling the whole thing. Done!
